name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache SBT ivy cache
      uses: actions/cache@v1.2.0
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
    - name: Cache SBT
      uses: actions/cache@v1.2.0
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Build assembly
      env:
        VERSION: $GITHUB_BUILD_NUMBER
      run: sbt assembly
    - name: Display the path
      run: ls -l $GITHUB_WORKSPACE/target/scala-2.13/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      env:
        VERSION: $GITHUB_BUILD_NUMBER
      with:
        # Artifact name
        name: assembly
        # A file, directory or wildcard pattern that describes what to upload
        path: $GITHUB_WORKSPACE/target/scala-2.13/ultimate-tictactoe-server-assembly-$VERSION.jar
